function varargout = battleshipUI(command, varargin)
% BATTLESHIPUI - UI-relaterede funktioner til Battleship-spillet
%
% Kommandoer:
%   'showWelcomeScreen' - Viser velkomstskærm
%   'showGameResult'    - Viser spillets resultat
%   'showInstructions'  - Viser spilleregler og instruktioner
%   'restartGame'       - Genstarter spillet
%   'showRulesContent'  - Opdaterer regeltekst
%   'showTipsContent'   - Opdaterer tips-tekst
%   'showShipsContent'  - Opdaterer skibstekst
%   
% Se hver specifik funktion for flere detaljer om input parametre.

    switch command
        case 'showWelcomeScreen'
            showWelcomeScreen(varargin{:});
        case 'showGameResult'
            showGameResult(varargin{:});
        case 'showInstructions'
            showInstructions(varargin{:});
        case 'restartGame'
            restartGame(varargin{:});
        case 'showRulesContent'
            showRulesContent(varargin{:});
        case 'showTipsContent'
            showTipsContent(varargin{:});
        case 'showShipsContent'
            showShipsContent(varargin{:});
        otherwise
            error('Ugyldig kommando: %s', command);
    end
end

function showWelcomeScreen(fig)
    % Overlay panel til velkomst med mere attraktivt design
    welcomePanel = uipanel('Parent', fig, 'Position', [0.25, 0.25, 0.5, 0.5], ...
        'Title', 'Velkommen til Battleship!', 'FontSize', 14, 'FontWeight', 'bold', ...
        'BackgroundColor', [0.9 0.95 1], 'HighlightColor', [0.2 0.4 0.8], ...
        'BorderWidth', 2);
    
    % Tilføj spilbeskrivelse med bedre formattering
    uicontrol('Parent', welcomePanel, 'Style', 'text', ...
        'Position', [20, 100, 460, 180], 'String', {...
        'SÅDAN SPILLER DU BATTLESHIP:', '', ...
        '1. Vælg sværhedsgrad og klik på "Start Spil"', ...
        '2. Placer dine 3 skibe ved at vælge orientering og klikke på dit bræt', ...
        '3. Skyd efter computerens skibe ved at klikke på modstanderens bræt', ...
        '4. Den første der sænker alle modstanderens skibe vinder!', ...
        '', ...
        'TIP: Når du placerer skibe, begynder du med det største skib først.'}, ...
        'FontSize', 11, 'HorizontalAlignment', 'left', ...
        'BackgroundColor', [0.9 0.95 1]);
    
    % Start spil-knap med mere tydelig styling
    uicontrol('Parent', welcomePanel, 'Style', 'pushbutton', ...
        'Position', [180, 30, 120, 40], 'String', 'Jeg er klar!', ...
        'FontSize', 12, 'FontWeight', 'bold', 'BackgroundColor', [0.3 0.6 0.3], ...
        'ForegroundColor', 'white', 'Callback', @(src,~) delete(welcomePanel));
end

function showGameResult(fig, isVictory)
    handles = getappdata(fig, 'handles');
    
    % Opret overlay panel med resultat - mere visuelt tiltalende
    resultPanel = uipanel('Parent', fig, 'Position', [0.3, 0.4, 0.4, 0.2], ...
        'BackgroundColor', [0.95 0.95 1], ...
        'HighlightColor', 'blue', 'BorderWidth', 2);
    
    if isVictory
        resultText = 'SEJR! Du sænkede alle modstanderens skibe!';
        textColor = [0 0.5 0];
        panelColor = [0.9 1 0.9];
    else
        resultText = 'NEDERLAG! Computeren sænkede alle dine skibe!';
        textColor = [0.8 0 0];
        panelColor = [1 0.9 0.9];
    end
    
    % Opdater baggrundsfarve baseret på resultat
    set(resultPanel, 'BackgroundColor', panelColor);
    
    % Tilføj tekst med bedre formattering
    uicontrol('Parent', resultPanel, 'Style', 'text', ...
        'Position', [20, 30, 320, 50], 'String', resultText, ...
        'FontSize', 14, 'FontWeight', 'bold', 'ForegroundColor', textColor, ...
        'BackgroundColor', panelColor);
    
    % Tilføj knap til at starte nyt spil - tydeligere styling
    uicontrol('Parent', resultPanel, 'Style', 'pushbutton', ...
        'Position', [120, 10, 120, 30], 'String', 'Spil igen', 'FontWeight', 'bold', ...
        'BackgroundColor', [0.3 0.6 0.3], 'ForegroundColor', 'white', ...
        'Callback', @(~,~) restartGame(handles.startButton, resultPanel));
end

function restartGame(startButton, resultPanel)
    % Hjælpefunktion til at fjerne resultatpanelet og starte et nyt spil
    delete(resultPanel);
    startGame(startButton, []);
end

function showInstructions(src, ~)
    % Forenklet version uden nested functions der løser problemet
    fig = ancestor(src, 'figure');
    
    % Opret simpel instruktionsfigur
    instructFig = figure('Name', 'Battleship Instruktioner', 'Position', [200, 200, 600, 450], ...
                       'MenuBar', 'none', 'NumberTitle', 'off', 'Color', [0.95 0.95 0.98]);
    
    % Opret tekstboksen først
    textBox = uicontrol('Parent', instructFig, 'Style', 'text', 'Position', [20, 20, 560, 380], ...
                     'String', '', 'BackgroundColor', [0.95 0.95 0.98], ...
                     'FontSize', 11, 'HorizontalAlignment', 'left');
    
    % Regler som standard
    showRulesContent(textBox);
    
    % Brug direkte callbacks med reference til textBox
    uicontrol('Parent', instructFig, 'Style', 'pushbutton', 'Position', [20, 410, 120, 30], ...
             'String', 'Spilleregler', 'Callback', @(~,~)showRulesContent(textBox), ...
             'BackgroundColor', [0.4 0.5 0.8], 'ForegroundColor', 'white');
             
    uicontrol('Parent', instructFig, 'Style', 'pushbutton', 'Position', [150, 410, 120, 30], ...
             'String', 'Tips & Tricks', 'Callback', @(~,~)showTipsContent(textBox), ...
             'BackgroundColor', [0.4 0.5 0.8], 'ForegroundColor', 'white');
             
    uicontrol('Parent', instructFig, 'Style', 'pushbutton', 'Position', [280, 410, 120, 30], ...
             'String', 'Skibe', 'Callback', @(~,~)showShipsContent(textBox), ...
             'BackgroundColor', [0.4 0.5 0.8], 'ForegroundColor', 'white');
end

function showRulesContent(textBox)
    set(textBox, 'String', {
        'SÅDAN SPILLER DU BATTLESHIP:', '', ...
        'FORMÅL:', ...
        '  Sænk alle modstanderens skibe før dine bliver sænket!', '', ...
        'GRIDKOORDINATER:', ...
        '  - Rækker er mærket med bogstaver (A, B, C, ...)', ...
        '  - Kolonner er mærket med tal (1, 2, 3, ...)', ...
        '  - Vælg position ved at klikke på brættet', '', ...
        'SPILLETS SYMBOLER:', ...
        '  - Blå felt: Dit skib', ...
        '  - Rødt felt med X: Træffer (ramt skib)', ...
        '  - O: Forbier (du ramte vand)', '', ...
        'GAMEPLAY:', ...
        '  1. Placer dine skibe på dit grid', ...
        '  2. Skift tur med computeren til at affyre skud', ...
        '  3. Den første der sænker alle fjendens skibe vinder!'
    });
end

function showTipsContent(textBox)
    set(textBox, 'String', {
        'TIPS TIL AT VINDE I BATTLESHIP:', '', ...
        '1. SKIBSPLACERING:', ...
        '  - Spred dine skibe ud over brættet', ...
        '  - Undgå at placere skibe langs kanten', ...
        '  - Prøv at placere skibe i uventede mønstre', '', ...
        '2. SKYDETAKTIK:', ...
        '  - Start med at skyde spredt over brættet', ...
        '  - Når du rammer et skib, prøv at skyde i alle fire retninger', ...
        '  - Følg rækken af hits for at sænke skibet', ...
        '  - Husk på skibenes forskellige længder (4, 3, 2)', ... 
        '', ...
        '3. SVÆRHEDSGRADER:', ...
        '  - Let: Computeren skyder tilfældigt', ...
        '  - Medium: Computeren fokuserer på at finde dine skibe', ...
        '  - Svær: Computeren bruger avanceret strategi og skakbrætmønster'
    });
end

function showShipsContent(textBox)
    set(textBox, 'String', {
        'SKIBSOVERSIGT:', '', ...
        '1. BATTLESHIP (SLAGSKIB)', ...
        '   Længde: 4 felter', ...
        '   Dette er dit største skib', '', ...
        '2. CRUISER (KRYDSER)', ...
        '   Længde: 3 felter', ...
        '   Medium størrelse skib', '', ...
        '3. DESTROYER (DESTROYER)', ...
        '   Længde: 2 felter', ...
        '   Dit mindste og hurtigste skib', '', ...
        'PLACERINGSTIPS:', ...
        '  - Vælg orientering (vandret eller lodret) før du klikker', ...
        '  - Du placerer skibene ét ad gangen, fra størst til mindst', ...
        '  - Skibene må ikke røre hinanden eller gå ud over brættet'
    });
end