function showInstructions(src, ~)
% SHOWINSTRUCTIONS - Viser spil-instruktioner i et nyt vindue
% Inputs:
%   src - Source handle for callback
    
    fig = ancestor(src, 'figure');
    
    % Vis instruktioner i en ny figur
    instructFig = figure('Name', 'Battleship Instruktioner', 'Position', [200, 200, 500, 400], ...
                       'MenuBar', 'none', 'NumberTitle', 'off');
    
    uicontrol('Parent', instructFig, 'Style', 'text', 'Position', [20, 20, 460, 360], ...
             'String', {
                 'SÅDAN SPILLER DU BATTLESHIP:', '', ...
                 'FORMÅL:', ...
                 '  Sænk alle modstanderens skibe før dine bliver sænket!', '', ...
                 'GRIDKOORDINATER:', ...
                 '  - Rækker er mærket med bogstaver (A, B, C, ...)', ...
                 '  - Kolonner er mærket med tal (1, 2, 3, ...)', ...
                 '  - Vælg position ved at klikke på brættet', '', ...
                 'SPILLETS SYMBOLER:', ...
                 '  - Blå felt: Dit skib', ...
                 '  - Rødt felt med X: Træffer (ramt skib)', ...
                 '  - O: Forbier (du ramte vand)', '', ...
                 'GAMEPLAY:', ...
                 '  1. Placer dine skibe på dit grid', ...
                 '  2. Skift tur med computeren til at affyre skud', ...
                 '  3. Den første der sænker alle fjendens skibe vinder!'
             }, ...
             'HorizontalAlignment', 'left');
end