function showInstructions(src, ~)
% SHOWINSTRUCTIONS - Shows game instructions in a new window
% Inputs:
%   src - Source handle for callback
    
    fig = ancestor(src, 'figure');
    
    % Show instructions in a new figure
    instructFig = figure('Name', 'Battleship Instructions', 'Position', [200, 200, 500, 400], ...
                       'MenuBar', 'none', 'NumberTitle', 'off');
    
    uicontrol('Parent', instructFig, 'Style', 'text', 'Position', [20, 20, 460, 360], ...
             'String', {
                 'HOW TO PLAY BATTLESHIP:', '', ...
                 'OBJECTIVE:', ...
                 '  Sink all of the opponent''s ships before yours are sunk!', '', ...
                 'GRID COORDINATES:', ...
                 '  - Rows are labeled with letters (A, B, C, ...)', ...
                 '  - Columns are labeled with numbers (1, 2, 3, ...)', ...
                 '  - Select position by clicking on the board', '', ...
                 'GAME SYMBOLS:', ...
                 '  - Blue square: Your ship', ...
                 '  - Red square with X: Hit (ship hit)', ...
                 '  - O: Miss (you hit water)', '', ...
                 'GAMEPLAY:', ...
                 '  1. Place your ships on your grid', ...
                 '  2. Take turns with the computer to fire shots', ...
                 '  3. The first to sink all enemy ships wins!'
             }, ...
             'HorizontalAlignment', 'left');
end