function showWelcomeScreen(fig)
% SHOWWELCOMESCREEN - Viser velkomstskærm når spillet starter
% Inputs:
%   fig - Handle til hovedfiguren
    
    % Overlay panel til velkomst
    welcomePanel = uipanel('Parent', fig, 'Position', [0.25, 0.25, 0.5, 0.5], ...
        'Title', 'Velkommen til Battleship!', 'FontSize', 14, ...
        'BackgroundColor', [0.95 0.95 1]);
    
    % Tilføj spilbeskrivelse
    uicontrol('Parent', welcomePanel, 'Style', 'text', ...
        'Position', [20, 100, 460, 180], 'String', {...
        'SÅDAN SPILLER DU BATTLESHIP:', '', ...
        '1. Vælg sværhedsgrad og klik på "Start Spil"', ...
        '2. Placer dine 3 skibe ved at vælge orientering og klikke på dit bræt', ...
        '3. Skyd efter computerens skibe ved at klikke på modstanderens bræt', ...
        '4. Den første der sænker alle modstanderens skibe vinder!', ...
        '', ...
        'Blå felter viser dine skibe', ...
        'X markerer ramt skib', ...
        'O markerer forbier (vand)'}, ...
        'FontSize', 11, 'HorizontalAlignment', 'left', ...
        'BackgroundColor', [0.95 0.95 1]);
    
    % Start spil-knap
    uicontrol('Parent', welcomePanel, 'Style', 'pushbutton', ...
        'Position', [180, 30, 120, 40], 'String', 'Jeg er klar!', ...
        'FontSize', 12, 'Callback', @(src,~) delete(welcomePanel));
end